lifestruct/config/routes.rb
Lifestruct::Application.routes.draw do

  get 'goals/calendar'
  get 'goals/assign'
  get 'goals/freetime'
  
  post 'goals/changegoaltime'
  resource :home
  resources :goals
  root 'homes#show'

  get 'goals/show_subgoals/:parentid' => 'goals#show_subgoals'

  

end

lifestruct/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lifestruct</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href=<%=root_path %>>Life Struct</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "Browse Goals", goals_path %></li>
            <li><%= link_to "Calendar", goals_calendar_path %></li>
            <li><%= link_to "Contact Us" %></li>
            <li><%= link_to "Create" %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <%= yield %> 
  </div>
</body>
</html>