lifestruct/config/routes.rb
Lifestruct::Application.routes.draw do

  get 'goals/calendar'
  get 'goals/assign'
  get 'goals/freetime'
  
  post 'goals/changegoaltime'
  resource :home
  resources :goals
  root 'homes#show'

  get 'goals/show_subgoals/:parentid' => 'goals#show_subgoals'

  

end

lifestruct/app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  def index
    @goals = Goal.all
    @root_goals = Goal.root_goals
  end

  def new
  end

  def show
    @goal = Goal.find(params[:id])
  end

  def edit
    @goal = Goal.find(params[:id])    
  end

  def update
    @new_goal = Goal.find(params[:id])
    title = goal_params[:title]
    description = goal_params[:description]
    #deadline = stringify_date(goal_params[:"deadline(1i)"], goal_params[:"deadline(2i)"], goal_params[:"deadline(3i)"], goal_params[:"deadline(4i)"], goal_params[:"deadline(5i)"])
    #starttime = stringify_date(goal_params[:"starttime(1i)"], goal_params[:"starttime(2i)"], goal_params[:"starttime(3i)"], goal_params[:"starttime(4i)"], goal_params[:"starttime(5i)"])
    #endtime =  stringify_date(goal_params[:"endtime(1i)"], goal_params[:"endtime(2i)"], goal_params[:"endtime(3i)"], goal_params[:"endtime(4i)"], goal_params[:"endtime(5i)"]) 
    
    deadline = parse_datetime(goal_params[:deadline])
    starttime = parse_datetime(goal_params[:start])
    endtime = parse_datetime(goal_params[:end])

    repeatable = goal_params[:repeatable].to_i
    hardcode_time = goal_params[:hardcode_time].to_i
    pick_color = goal_params[:pick_color].to_i
    background_color = goal_params[:background_color]
    border_color = goal_params[:border_color]
    monday_stat = goal_params[:repeat1]
    tuesday_stat = goal_params[:repeat2]
    wednesday_stat = goal_params[:repeat3]
    thursday_stat = goal_params[:repeat4]
    friday_stat = goal_params[:repeat5]
    saturday_stat = goal_params[:repeat6]
    sunday_stat = goal_params[:repeat7]
    month_stat = goal_params[:repeat8]
    all_stats = [monday_stat, tuesday_stat, wednesday_stat, thursday_stat, friday_stat, saturday_stat, sunday_stat, month_stat]
    parent_id = goal_params[:parent_id]

    if pick_color == 0
      background_color = nil
      border_color = nil
    end

    if parent_id.empty?
      parent_id = nil
    else
      parent_id = parent_id.to_i
      parent_goal = Goal.find(parent_id)
      parent_goal.update_attribute(:has_child, 1)
      if pick_color == 0
        background_color = parent_goal.background_color
        border_color = parent_goal.border_color
      end
    end

    if hardcode_time == 1
      deadline = nil
    else
      starttime = nil
      endtime = nil
      time_alloc = goal_params[:timetaken]
    end

    repeat_stat = nil
    if repeatable == 1
      rep_string = ""
      all_stats.each_with_index do |stat, index|
        if stat == "1"
          rep_string += (index + 1).to_s
        end
      end
      repeat_stat = rep_string.to_i
    end

    @new_goal.assign_attributes({title: title,
       description: description,
       deadline: deadline,
       start: starttime,
       repeatable: repeat_stat,
       :end => endtime,
       parent_id: parent_id,
       timetaken: time_alloc,
       background_color: background_color,
       border_color: border_color
      })
    @new_goal.save
    unless @new_goal.timetaken
      time_taken = (@new_goal.end.to_time - @new_goal.start.to_time)/60
      @new_goal.update_attribute(:timetaken, time_taken)
    end
    redirect_to goals_path    

    # respond_to do |format|
    #   if @goal.update(goal_params)
    #     format.html { redirect_to @post, notice: 'Post was successfully updated.' }
    #     format.json { head :no_content }
    #   else
    #     format.html { render action: 'edit' }
    #     format.json { render json: @post.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  def assign
    Goal.assign_goals
    redirect_to '/home', notice: "All unassigned goals have been successfully assigned."   
  end

  def destroy
    @del_goal = Goal.find(params[:id])
    @sub_goals = @del_goal.subgoals
    @sub_goals.each do |subgoal|
      if subgoal.goal_map
        subgoal.goal_map.destroy
      end
      subgoal.destroy
    end
    @del_goal.goal_map.destroy if @del_goal.goal_map
    @del_goal.destroy
    redirect_to '/goals', notice: "successfully deleted."
  end

  def parse_datetime(str)
    Chronic.parse(str)
  end
  
  def create
    @new_goal = Goal.new
    title = goal_params[:title]
    description = goal_params[:description]
    #deadline = stringify_date(goal_params[:"deadline(1i)"], goal_params[:"deadline(2i)"], goal_params[:"deadline(3i)"], goal_params[:"deadline(4i)"], goal_params[:"deadline(5i)"])
    #starttime = stringify_date(goal_params[:"starttime(1i)"], goal_params[:"starttime(2i)"], goal_params[:"starttime(3i)"], goal_params[:"starttime(4i)"], goal_params[:"starttime(5i)"])
    #endtime =  stringify_date(goal_params[:"endtime(1i)"], goal_params[:"endtime(2i)"], goal_params[:"endtime(3i)"], goal_params[:"endtime(4i)"], goal_params[:"endtime(5i)"]) 
    
    deadline = parse_datetime(goal_params[:deadline])
    starttime = parse_datetime(goal_params[:start])
    endtime = parse_datetime(goal_params[:end])

    repeatable = goal_params[:repeatable].to_i
    hardcode_time = goal_params[:hardcode_time].to_i
    pick_color = goal_params[:pick_color].to_i
    background_color = goal_params[:background_color]
    border_color = goal_params[:border_color]
    monday_stat = goal_params[:repeat1]
    tuesday_stat = goal_params[:repeat2]
    wednesday_stat = goal_params[:repeat3]
    thursday_stat = goal_params[:repeat4]
    friday_stat = goal_params[:repeat5]
    saturday_stat = goal_params[:repeat6]
    sunday_stat = goal_params[:repeat7]
    month_stat = goal_params[:repeat8]
    all_stats = [monday_stat, tuesday_stat, wednesday_stat, thursday_stat, friday_stat, saturday_stat, sunday_stat, month_stat]
    parent_id = goal_params[:parent_id]

    if pick_color == 0
      background_color = nil
      border_color = nil
    end

    if parent_id.empty?
      parent_id = nil
    else
      parent_id = parent_id.to_i
      parent_goal = Goal.find(parent_id)
      parent_goal.update_attribute(:has_child, 1)
      if pick_color == 0
        background_color = parent_goal.background_color
        border_color = parent_goal.border_color
      end
    end

    if hardcode_time == 1
      deadline = nil
    else
      starttime = nil
      endtime = nil
      time_alloc = goal_params[:timetaken]
    end

    repeat_stat = nil
    if repeatable == 1
      rep_string = ""
      all_stats.each_with_index do |stat, index|
        if stat == "1"
          rep_string += (index + 1).to_s
        end
      end
      repeat_stat = rep_string.to_i
    end

    @new_goal.assign_attributes({title: title,
       description: description,
       deadline: deadline,
       start: starttime,
       repeatable: repeat_stat,
       :end => endtime,
       parent_id: parent_id,
       timetaken: time_alloc,
       background_color: background_color,
       border_color: border_color
      })
    @new_goal.save
    unless @new_goal.timetaken
      time_taken = (@new_goal.end.to_time - @new_goal.start.to_time)/60
      @new_goal.update_attribute(:timetaken, time_taken)
    end
    redirect_to goals_path
  end

  def changegoaltime
    goal = Goal.find(params[:id])
    if params[:set_new] == "true"
      startt = DateTime.parse(params[:start]).change(offset: "+0530")
      endt = DateTime.parse(params[:end]).change(offset: "+0530")  
      @goal = Goal.new({title: goal.title,
                        description: goal.description,
                        deadline: goal.deadline,
                        start: startt,
                        :end => endt,
                        parent_id: goal.parent_id,
                        timetaken: ((endt.to_time - startt.to_time)/60),
                        background_color: goal.background_color,
                        border_color: goal.border_color
                      })
      @goal.save
      @goal.assign(status: Goal.FIXED)
      if goal.goal_map.blacklist
        goal.goal_map.blacklist = goal.goal_map.blacklist + " " + @goal.id.to_s
      else
        goal.goal_map.blacklist = @goal.id.to_s
      end
      goal.goal_map.save
    else
      goal.start = DateTime.parse(params[:start]).change(offset: "+0530")
      goal.end = DateTime.parse(params[:end]).change(offset: "+0530")
      goal.save
    end
    redirect_to home_path
  end

  def string_to_datetime(year, month, day, hour, min)
    DateTime.new(year.to_i, month.to_i, day.to_i, hour.to_i, min.to_i).change(offset: "+0530")
  end

  def freetime
    #starttime = string_to_datetime(goal_params[:"starttime(1i)"], goal_params[:"starttime(2i)"], goal_params[:"starttime(3i)"], goal_params[:"starttime(4i)"], goal_params[:"starttime(5i)"])
    #endtime =  string_to_datetime(goal_params[:"endtime(1i)"], goal_params[:"endtime(2i)"], goal_params[:"endtime(3i)"], goal_params[:"endtime(4i)"], goal_params[:"endtime(5i)"]) 
    starttime = parse_datetime(goal_params[:starttime]).to_datetime
    endtime = parse_datetime(goal_params[:endtime]).to_datetime
    displaced_goals = Goal.free_time_between(starttime, endtime)
    displaced_goals.each {|goal| goal.assign({status: Goal.FLUID, date_range: [endtime, goal.deadline.to_datetime]})}
    redirect_to '/home'
  end

  def stringify_date(year, month, day, hour, min)
    datetime = "#{year}-#{month}-#{day} #{hour}:#{min}"
  end

  def calendar
    @asgn_goals = []
    start_date = build_date_from_date_string(params[:start])
    fin_date = build_date_from_date_string(params[:end])
    GoalMap.all.map{ |gm| gm.goal }.each do |goal|
      if goal.repeatable
        goals = goal.all_reps_in_bw(start_date, fin_date)
        goals.each do |goal|
          goal.start = goal.start.to_s
          goal.end = goal.end.to_s
        end
        @asgn_goals.push(goals)
      else
        goal.start = goal.start.to_s
        goal.end = goal.end.to_s
        @asgn_goals.push(goal)
      end
    end
    @asgn_goals.flatten!
    respond_to do |format|
      format.json
      format.html
    end
  end

  def build_date_from_date_string(date_string)
    if date_string.present?

lifestruct/app/helpers/goals_helper.rb
module GoalsHelper

  def format_datetime(datetime)
    datetime.strftime("%b %e, %a, %l:%M %p")
  end

  def decode_rep_code(rep_code)
    decoded_str = ""
    rep_code_len = rep_code.to_s.length
    index = 0
    rep_code.to_s.each_char do |char|
      index += 1
      if index == rep_code_len
        decoded_str = decoded_str + "and " + Goal.DAY_MAP[char.to_i] + "."
      else 
        decoded_str = decoded_str + Goal.DAY_MAP[char.to_i] + ", "
      end
    end
    decoded_str = (Goal.DAY_MAP[rep_code] + ".") if rep_code_len == 1
    decoded_str
  end
end

lifestruct/app/views/goals/_edit.html.erb
<%= bootstrap_form_for(:goal, url: goal_path, method: :patch) do |f| %>
  <%= f.text_field :title, class: 'span4' %>
  <%= f.text_area :description, class: 'span4', :cols => "20", :rows => "6", placeholder: "Describe the goal..." %>
  <%= f.check_box :pick_color, label: "Pick Color (uncheck for default/inherit from parent)"%>
  <div id="color-select-goal">
    <%= f.text_field :background_color, class: "colorpicker" %>
    <%= f.text_field :border_color, class: "colorpicker" %>
  </div>
  <%= f.check_box :repeat, label: "Goal Repeats" %>
  <div id="repeat-stat-form" style="margin-left: 20px; padding-bottom: 10px; padding-top: 10px;">
  <%= f.form_group :repeatstat, label: { text: "Repeats every..." } do %>
    <%= f.check_box :repeat1 do %>
      Monday
    <% end %>
    <%= f.check_box :repeat2 do %>
      Tuesday
    <% end %>
    <%= f.check_box :repeat3 do %>
      Wednesday
    <% end %>
    <%= f.check_box :repeat4 do %>
      Thursday
    <% end %>
    <%= f.check_box :repeat5 do %>
      Friday
    <% end %>
    <%= f.check_box :repeat6 do %>
      Saturday
    <% end %>
    <%= f.check_box :repeat7 do %>
      Sunday
    <% end %>
    <%= f.check_box :repeat8 do %>
      Month
    <% end %>
  <% end %>
  </div>
  <%= f.check_box :hardcode_time, label: "Manually Set Time" %>
  <div id="hardcode-time">
    <%= f.text_field :start, placeholder: "#{Time.now}" %>
    <%= f.text_field :end, placeholder: "#{Time.now + (60*60)}" %>
  </div>
  <div id="deadline-select-div">
    <%= f.number_field :timetaken, placeholder: "0" %>
    <%= f.text_field :deadline, placeholder: "#{Time.now}" %>
  </div>
  <%= f.hidden_field :parent_id %>
  <%= f.submit class: 'btn btn-primary', style: 'float: right;' %>
<% end %>

lifestruct/app/views/goals/_goaly.html.erb
<li id="goal-id-<%= goal.id %>">
  <div class="goal">
  <h3> <%= goal.title %>  </h3>
  <p> <%= goal.description %> </p>
  <% if goal.subgoals.length == 0 %>
    <% if goal.repeatable %> 
      <p> <strong> Repeats every </strong> <%= decode_rep_code goal.repeatable %> </p>
    <% end %>
    <% if goal.deadline %>
      <p> <strong>Deadline:</strong> <%= format_datetime goal.deadline %> </p>
    <% end %>
    <% if goal.start %>
      <p> <strong>Start Time:</strong> <%= format_datetime goal.start %> </p>
    <% end %>
    <% if goal.end %>
      <p> <strong>End Time:</strong> <%= format_datetime goal.end %> </p>
    <% end %>
  <% end %>
  <button type="button" class="btn btn-primary btn-small add-goal-button" data-toggle="modal" data-target="#myModal" id="parent-<%= goal.id %>">
    <i class="icon-plus icon-white"></i> 
  </button>
  <% if goal.subgoals.length > 0 %>
    <%= link_to "/goals/show_subgoals/#{goal.id}", class: "btn btn-small", id: "show-parent-#{goal.id}", remote: true do %>
      <i class="icon-chevron-down icon-white"></i>
    <% end %>
  <% end %>
  <%= link_to "/goals/#{goal.id}/edit", class: "btn btn-small btn-warning" do %>
    <i class="icon-pencil icon-white"></i>
  <% end %>
  <%= link_to "/goals/#{goal.id}", class: "btn btn-small btn-danger", method: :delete, confirm: "Are you sure?" do %>
    <i class="icon-remove icon-white"></i>
  <% end %>
  <ul id="ul-parent-<%=goal.id %>"></ul>
  </div>
</li>

lifestruct/app/views/goals/calendar.html.erb
<h2> <%= @current_date %> </h2>

<% @asgn_goals.each do |goal| %>
  <p><strong><%= format_datetime(goal.start) %> — <%= format_datetime(goal.end) %></strong> <%= goal.title %></p>
<% end %>

lifestruct/app/views/goals/edit.html.erb
<script>
$(document).ready(function() {
  $("#repeat-stat-form").hide();
  $("#hardcode-time").hide();
  $(".colorpicker").colorpicker();
  $("#color-select-goal").hide();
});
$(document).on("click", ".add-goal-button", function(e) {
  var btnid = $(this).attr('id');
  var parent_id = btnid.split("-")[1];
  $('#goal_parent_id').attr('value', parent_id);
  console.log(parent_id);
});

$(document).on("click", "#goal_repeat", function(e) {
  var val_stat = $(this).is(":checked");
  if (val_stat) {
    $("#repeat-stat-form").show();
  } else {
    $("#repeat-stat-form").hide();
  }
});

$(document).on("click", "#goal_hardcode_time", function(e) {
  var val_stat = $(this).is(":checked");
  if (val_stat) {
    $("#hardcode-time").show();
    $("#deadline-select-div").hide();
  } else {
    $("#hardcode-time").hide();
    $("#deadline-select-div").show();
  }
});

$(document).on("click", "#goal_pick_color", function(e) {
  var val_stat = $(this).is(":checked");
  if (val_stat) {
    $("#color-select-goal").show();
  } else {
    $("#color-select-goal").hide();
  }
});

</script>


<h2> Editing </h2>
<%= render 'edit' %>

lifestruct/app/views/goals/index.html.erb
<script>
$(document).ready(function() {
  $("#repeat-stat-form").hide();
  $("#hardcode-time").hide();
  $(".colorpicker").colorpicker();
  $("#color-select-goal").hide();
});
$(document).on("click", ".add-goal-button", function(e) {
  var btnid = $(this).attr('id');
  var parent_id = btnid.split("-")[1];
  $('#goal_parent_id').attr('value', parent_id);
  console.log(parent_id);
});

$(document).on("click", "#goal_repeatable", function(e) {
  var val_stat = $(this).is(":checked");
  if (val_stat) {
    $("#repeat-stat-form").show();
  } else {
    $("#repeat-stat-form").hide();
  }
});

$(document).on("click", "#goal_hardcode_time", function(e) {
  var val_stat = $(this).is(":checked");
  if (val_stat) {
    $("#hardcode-time").show();
    $("#deadline-select-div").hide();
  } else {
    $("#hardcode-time").hide();
    $("#deadline-select-div").show();
  }
});

$(document).on("click", "#goal_pick_color", function(e) {
  var val_stat = $(this).is(":checked");
  if (val_stat) {
    $("#color-select-goal").show();
  } else {
    $("#color-select-goal").hide();
  }
});

</script>

<h2> All Goals </h2>
<ul class="goals">
  <% @root_goals.each do |goal| %>
    <%= render 'goaly', goal: goal %>
  <% end %>
</ul>
<!-- Button trigger modal -->


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Make a New Goal</h4>
      </div>
      <div class="modal-body">
        <%= render 'homes/form' %>
      </div>
    </div>
  </div>
</div>

lifestruct/app/views/goals/show.html.erb
<script>
$(document).ready(function() {
  $("#repeat-stat-form").hide();
  $("#hardcode-time").hide();
  $(".add-goal-button").hide();
});
$(document).on("click", ".add-goal-button", function(e) {
  var btnid = $(this).attr('id');
  var parent_id = btnid.split("-")[1];
  $('#goal_parent_id').attr('value', parent_id);
  console.log(parent_id);
});


</script>

<ul class="goals">
  <%= render 'goaly', goal: @goal %>
</ul>
<!-- Button trigger modal -->

lifestruct/app/views/goals/show_subgoals.js.erb
if ($("<%= escape_javascript @ul_con %> li").length == 0) {
  $("<%= escape_javascript @show_sg_icn_path %>").attr('class', 'icon-chevron-up icon-white');
  <% @subgoals.each do |subgoal| %>
    $("<%= escape_javascript @ul_con %>").append("<%= escape_javascript render 'goaly', goal: subgoal %>");
  <% end %>
} else {
  $("<%= escape_javascript @show_sg_icn_path %>").attr('class', 'icon-chevron-down icon-white');
  $("<%= escape_javascript @ul_con %>").empty();
}